# Generated by Django 5.1.1 on 2025-04-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="cancelado",
            field=models.BooleanField(default=False),
        ),
    ]
